# Generated by Django 2.2 on 2019-04-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mytest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mytest_test', to='startpage.Test'),
        ),
        migrations.AlterField(
            model_name='mytest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mytest_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_correct_answer', to='startpage.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_test', to='startpage.Test'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='mytest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mytest', to='startpage.MyTest'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='startpage.Question'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='selected_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answer', to='startpage.Answer'),
        ),
    ]
