# Generated by Django 2.2 on 2019-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_auto_20190414_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
