# Generated by Django 2.2 on 2019-04-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_test_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
    ]
