# Generated by Django 2.2 on 2019-04-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0007_auto_20190427_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='mytest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mytests', to='startpage.MyTest'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='startpage.Question'),
        ),
    ]
