# Generated by Django 2.2 on 2019-04-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0008_auto_20190427_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answer', to='startpage.Answer'),
        ),
    ]
