# Generated by Django 2.2 on 2019-04-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0009_auto_20190427_0927'),
        ('startpage', '0007_auto_20190426_1540'),
    ]

    operations = [
    ]
