# Generated by Django 2.2 on 2019-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0010_merge_20190427_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytest',
            name='achieved_level',
            field=models.IntegerField(default=1),
        ),
    ]
